//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AastapanaForm_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Section2
    {
        public int Id { get; set; }
        public string TaskDuringPost { get; set; }
        public string AllocatedTask { get; set; }
        public string WorksInWork { get; set; }
        public string Diffi_In_Targets { get; set; }
        public string Area_Requi_Train { get; set; }
        public string Asset_Submit_Status { get; set; }
        public string Login_ID { get; set; }
    }
}
