//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AastapanaForm_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Section4
    {
        public int Id { get; set; }
        public string Login_ID { get; set; }
        public string Agree_assessment_sect3 { get; set; }
        public string Diff_opinion { get; set; }
        public string Overall_assessment_officer { get; set; }
        public string Overall_graduation { get; set; }
    }
}
