//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AastapanaForm_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Section1
    {
        public int Id { get; set; }
        public string Employee_Name { get; set; }
        public string Cadre { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Present_Post { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public string Department { get; set; }
        public string ReportingOfficerName { get; set; }
        public string ReportingOfficerDesign { get; set; }
        public string ReportingOfficerPeriod { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string ReviewingOfficerName { get; set; }
        public string ReviewingOfficerDesign { get; set; }
        public string ReviewingOfficerPeriod { get; set; }
        public string LeavePeriod { get; set; }
        public string LeaveType { get; set; }
        public string LeaveRemark { get; set; }
        public string UnAuthAbsencePeriod { get; set; }
        public string UnAuthAbsenceType { get; set; }
        public string UnAuthAbsenceRemark { get; set; }
        public Nullable<System.DateTime> TrainingFrom { get; set; }
        public Nullable<System.DateTime> TrainingTo { get; set; }
        public string TrainingInstitute { get; set; }
        public string TrainingSubject { get; set; }
        public Nullable<System.DateTime> DateOfFillingAssets { get; set; }
        public string Login_ID { get; set; }
    }
}
