//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AastapanaForm_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Section3
    {
        public int Id { get; set; }
        public string Login_ID { get; set; }
        public string Agree_Self_assess { get; set; }
        public string Work_Self_assess_Report { get; set; }
        public string FailureInwork_Details { get; set; }
        public string Skill_upgra_Center { get; set; }
        public string Rating_On_Efficiency { get; set; }
        public string Work_Reporting_Officer { get; set; }
        public string Op_Reporting_Officer { get; set; }
        public string Accom_Reporting_Officer { get; set; }
        public string Avg_Grad_work_Reporting_Officer { get; set; }
        public string Work_Review_Officer { get; set; }
        public string Op_Review_Officer { get; set; }
        public string Accom_Review_Officer { get; set; }
        public string Avg_Grad_work_Review_Officer { get; set; }
        public string Atti_Work_Repo_Officer { get; set; }
        public string Sence_Respo_Repo_Officer { get; set; }
        public string Bearing_Person_Repo_Officer { get; set; }
        public string Emotional_Stability_Repo_Officer { get; set; }
        public string Commu_Skills_Repo_Officer { get; set; }
        public string CapacityOf_Work_Repo_Officer { get; set; }
        public string Avg_Gradation_Person_Attri_Repo_Officer { get; set; }
        public string Atti_Work_Review_Officer { get; set; }
        public string Sence_Respo_Review_Officer { get; set; }
        public string Bearing_Person_Review_Officer { get; set; }
        public string Emotional_Stability_Review_Officer { get; set; }
        public string Commu_Skills_Review_Officer { get; set; }
        public string CapacityOf_Work_Review_Officer { get; set; }
        public string Avg_Gradation_Person_Attri_Review_Officer { get; set; }
        public string Knowldge_Skill_Repo_Officer { get; set; }
        public string Strategic_Planning_Ability_Repo_Officer { get; set; }
        public string Decision_Ability_Repo_Officer { get; set; }
        public string Initiative_Repo_Officer { get; set; }
        public string Co_Ordinate_Agencies_Repo_Officer { get; set; }
        public string Avg_Grade_Work_Effi_Repo_Officer { get; set; }
        public string Knowldge_Skill_Review_Officer { get; set; }
        public string Strategic_Planning_Ability_Review_Officer { get; set; }
        public string Decision_Ability_Review_Officer { get; set; }
        public string Initiative_Review_Officer { get; set; }
        public string Co_Ordinate_Agencies_Review_Officer { get; set; }
        public string Avg_Grade_Work_Effi_Review_Officer { get; set; }
        public string Remark_Character_Integrity { get; set; }
        public string Overall_Assessment_Officer { get; set; }
        public string Strength_atti_to_abnormal_person { get; set; }
        public string State_of_Mind { get; set; }
        public string Overall_Graduation { get; set; }
    }
}
